### ISSUE TITLE
Can we overlap the enemy health and buildup bars?

### ISSUE THREAD

**Issue by matiascodesal** [ElBruh/CDN_Game#17]
Right, the bars become staggered after damage is applied and it becomes harder to understand.  Here's what I was thinking for the build up.  

![enemy_health_bar](https://user-images.githubusercontent.com/8684094/41501931-92388e52-7162-11e8-96b5-7736f0e14dc7.png)

**Comment by ElBruh** [comment]
Yas

**Comment by matiascodesal** [comment]
Nice!  Looking good.

I think there's a bug?  If I complete 1 word on round 1, the damage is applied.  On round 2, the damage to apply carries over.  I can choose not to complete a word on round 2 and the enemy will die from the damage that's carried over.

Or new feature?  Hero applies poison damage over time. :)
